plantometer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.shortcuts import redirect
from django.views.generic.base import RedirectView
from . import views
from django.contrib.auth import views as v

urlpatterns = [
	#url(r'^$', RedirectView.as_view(url='/users/')),
	url(r'^$', views.homepage, name='homepage'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    
    url(r'^sensors/', include('sensors.urls', namespace='sensors')),
    url(r'^logout/$', v.logout , {'next_page': '/'}),
    
]

users/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

from django.contrib.auth import views as v
from sensors.forms import LoginForm

app_name = 'users'

urlpatterns = [

	url(r'^homepage$', views.homepage, name='homepage'),
	url(r'^loginpage/$', views.signUp, name='loginpage'),
	url(r'^data/$', views.temperature, name='data'),
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', v.logout , {'next_page': '/'}, name='logout'), 
	url(r'', include('sensors.urls')),
	url(r'^addplant/$', views.addplant, name='addplant'),
	url(r'^addvehicle/$', views.addVehicle, name='addVehicle'),
	url(r'^addmember/$', views.addMember, name='addMember'),
	url(r'^addReservoir/$', views.addReservoir, name='addReservoir'),
	url(r'^api/login/$', views.mobile_login, name='mobile_login'),
]

users/models.py
from __future__ import unicode_literals
from django.db import models
from django import forms
from django.core.urlresolvers import reverse


class Users(models.Model):
	name = models.CharField(max_length=50)
	password = models.CharField(max_length=70)
	phone = models.CharField(max_length = 15, unique=True)
	address = models.CharField(max_length=150)
	currentplant = models.CharField(max_length = 50, null = True)
	currentreservoir = models.IntegerField(default = 0)
	plantcount = models.IntegerField(default = 0)
	vehicleCount = models.IntegerField(default = 0)
	membercount = models.IntegerField(default = 0)
	reservoircount = models.IntegerField(default = 0)

	def get_absolute_url(self):
		return reverse('users:login')

	def __str__(self):
		return self.name

class Plants(models.Model):
	userid = models.ForeignKey(Users, on_delete=models.CASCADE)
	plantName = models.CharField(max_length = 50)

	def __str__(self):
		return self.plantName

class Members(models.Model):
	userid = models.ForeignKey(Users, on_delete = models.CASCADE)
	memberName = models.CharField(max_length = 50)

	def __str__(self):
		return self.memberName

class Vehicles(models.Model):
	userid = models.ForeignKey(Users, on_delete = models.CASCADE)
	vehicle = models.CharField(max_length = 50)

	def __str__(self):
		return self.vehicle

users/views.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from django.conf.urls import url, include
from .models import Users, Plants, Vehicles, Members
from sensors.models import reservoir, reservoirdata
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json
userid = -1
def homepage(request):
	return render(request, 'users/index.html')

def loginpage(request):
	return render(request, 'users/login.html')

def temperature(request):
	return render(request, 'users/index.html')

def signUp(request):
	if request.POST:
		t = Users(name=request.POST['name'],password=request.POST['password'],phone=request.POST['username'],address=request.POST['address'])
		t.save()		
		return redirect('../login')
	return render(request, 'users/loginpage.html')

def login(request):
	r = False
	if request.POST:
		t = Users.objects.filter(password=request.POST['password'],phone=request.POST['username'])
		if len(t):
			request.session['name'] = t[0].name
			request.session['id'] = t[0].id
			global userid
			userid = t[0].id
			return redirect('../../sensors/data')
		else:
			messages.error(request, 'no such user')
			return render(request, 'users/login.html')
	return render(request, 'users/login.html',{"r":r})

def addplant(request):
	r = False
	if request.POST:
		global userid
		uid = userid
		z = get_object_or_404(Users, pk=userid)
		f = Plants.objects.filter(userid = z)
		z.plantcount += 1
		if f:
			p = Plants(userid = z, plantName = request.POST['plantname'])
			p.save()
		else:
			p = Plants(userid = z, plantName = request.POST['plantname'])
			p.save()
			z.currentplant = p.id
			z.save()
		z = Plants.objects.filter(userid = userid)
		return redirect('../../sensors/data')
	return render(request, 'users/addplant.html')

def addReservoir(request):
	r = False
	if request.POST:
		global userid
		uid = userid
		z = get_object_or_404(Users, pk=userid)
		f = reservoir.objects.filter(userid = z)
		z.reservoircount += 1
		z.save()
		if f:
			p = reservoir(userid = z, reservoirname = request.POST['reservoirname'])
			p.save()
		else:
			p = reservoir(userid = z, reservoirname = request.POST['reservoirname'])
			p.save()
			z.currentreservoir = p.id
			z.save()
		z = reservoir.objects.filter(userid = userid)
		return redirect('../../sensors/data')
	return render(request, 'users/addReservoir.html')

def addVehicle(request):
	if request.POST:
		global userid
		z = get_object_or_404(Users, pk=userid)
		v = Vehicles(userid = z, vehicle = request.POST['vehiclename'])
		v.save()
		z.vehicleCount += 1
		z.save()
		return redirect('../../sensors/data')
	return render(request, 'users/addVehicle.html')

def addMember(request):
	if request.POST:
		global userid
		z = get_object_or_404(Users, pk=userid)
		v = Members(userid = z, memberName = request.POST['membername'])
		v.save()
		z.membercount += 1
		z.save()
		return redirect('../../sensors/data')
	return render(request, 'users/addMember.html')



# ----------------- API --------------------

@csrf_exempt
def mobile_login(request):
	if request.method=='POST':
		jsonResponse=json.loads(request.body.decode('utf-8'))
		username=jsonResponse['json_data']['username']
		password=jsonResponse['json_data']['password']
		print(password)
		t = Users.objects.filter(password=password,phone=username)

		if len(t):
			#request.session['name'] = t[0].name
			#request.session['id'] = t[0].id

			global userid
			userid = t[0].id
			u={"pass":"true","id":t[0].id,"name":t[0].name,"phone":t[0].phone,"address":t[0].address,"currentplant":t[0].currentplant,"vehicleCount":t[0].vehicleCount,"membercount":t[0].membercount}
			return JsonResponse(u)
		else:
			u={"pass":"false"}
			return JsonResponse(u)

users/templates/users/addMember.html
<html>
    <head>

        {% load staticfiles %}
        <title>DILUTE</title>
        <script src="https://use.fontawesome.com/a2c08f3da1.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
        <link rel="shortcut icon" href="{% static 'users/img/logo-image.jpg' %}">
    </head>
    <body style="background-image: url({% static 'users/img/bg/main1.jpg' %});">
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'users:homepage' %}">Home </a>
                    </li>
                </ul>
                {% if 'name' in request.session %}
                    Hello {{ request.session.name }} !
                {% endif %}
                <ul class="navbar-nav ml-auto">
                    <!--li class="nav-item">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact Us</a>
                    </li-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sensors:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="login-page">
            <div class="form">
                <center>
                    <form name="myform1" role="form" action="{% url 'users:addMember' %}" method="post" class="register-form">
                    <img src="{% static 'users/img/logo-image.jpg' %}" alt="" height="150px" width="150px" />
                        <!-- <img src="{% static 'users/img/logo-image.png' %}" alt="" height="150" width="150" /> -->
                        {% csrf_token %}
                        <input type="text" name="membername" placeholder="MEMBER NAME"><br><br>
                        <button type="submit">Add Member</button>
                    </form>
                </center>
            </div>
        </div>
    </body>
    
    <script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{% static 'sensors/js/Rx.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<style>
.login-page {
  width: 370px;
  padding: 10% 0 0;
  margin: auto;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 50px;
  padding: 30px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 50px;
  padding: 30px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 10px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #4CAF50;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.form button:hover,.form button:active,.form button:focus {
  background: #43A047;
}
body {
  /*background: #76b852; /* fallback for old browsers 
  background-image: url({% static 'users/img/bg/bg-9.jpg' %});*/
  background: -webkit-linear-gradient(right, #76b852, #8DC26F);
  background: -moz-linear-gradient(right, #76b852, #8DC26F);
  background: -o-linear-gradient(right, #76b852, #8DC26F);
  background: linear-gradient(to left, #76b852, #8DC26F);
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;      
}

</style>
</html>

users/templates/users/addReservoir.html
<html>
    <head>

        {% load staticfiles %}
        <title>DILUTE</title>
        <script src="https://use.fontawesome.com/a2c08f3da1.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
        <link rel="shortcut icon" href="{% static 'users/img/logo-image.jpg' %}">
    </head>
    <body style="background-image: url({% static 'users/img/bg/main1.jpg' %});">
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'users:homepage' %}">Home </a>
                    </li>
                </ul>
                {% if 'name' in request.session %}
                    Hello {{ request.session.name }} !
                {% endif %}
                <ul class="navbar-nav ml-auto">
                    <!--li class="nav-item">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact Us</a>
                    </li-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sensors:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="login-page">
            <div class="form">
                <center>
                    <form name="myform1" role="form" action="{% url 'users:addReservoir' %}" method="post" class="register-form">
                        <img src="{% static 'users/img/logo-image.jpg' %}" alt="" height="150px" width="150px" />
                        <!-- <img src="{% static 'users/img/logo-image.png' %}" alt="" height="150" width="150" /> -->
                        {% csrf_token %}
                        <input type="text" name="reservoirname" placeholder="RESERVOIR NAME"><br><br>
                        <button type="submit">Add Reservoir</button>
                    </form>
                </center>
            </div>
        </div>
    </body>
    
    <script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{% static 'sensors/js/Rx.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<style>
.login-page {
  width: 370px;
  padding: 10% 0 0;
  margin: auto;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 50px;
  padding: 30px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 50px;
  padding: 30px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 10px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #4CAF50;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.form button:hover,.form button:active,.form button:focus {
  background: #43A047;
}
body {
  /*background: #76b852; /* fallback for old browsers 
  background-image: url({% static 'users/img/bg/bg-9.jpg' %});*/
  background: -webkit-linear-gradient(right, #76b852, #8DC26F);
  background: -moz-linear-gradient(right, #76b852, #8DC26F);
  background: -o-linear-gradient(right, #76b852, #8DC26F);
  background: linear-gradient(to left, #76b852, #8DC26F);
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;      
}

</style>
</html>

users/templates/users/addVehicle.html
<html>
    <head>

        {% load staticfiles %}
        <title>DILUTE</title>
        <script src="https://use.fontawesome.com/a2c08f3da1.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
        <link rel="shortcut icon" href="{% static 'users/img/logo-image.jpg' %}">
    </head>
    <body style="background-image: url({% static 'users/img/bg/main1.jpg' %});">
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'users:homepage' %}">Home </a>
                    </li>
                </ul>
                {% if 'name' in request.session %}
                    Hello {{ request.session.name }} !
                {% endif %}
                <ul class="navbar-nav ml-auto">
                    <!--li class="nav-item">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact Us</a>
                    </li-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sensors:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="login-page">
            <div class="form">
                <center>

                    <form name="myform1" role="form" action="{% url 'users:addVehicle' %}" method="post" class="register-form">
                    <img src="{% static 'users/img/logo-image.jpg' %}" alt="" height="150px" width="150px" />
                        <!-- <img src="{% static 'users/img/logo-image.png' %}" alt="" height="150" width="150" /> -->
                        {% csrf_token %}
                        <input type="text" name="vehiclename" placeholder="VEHICLE NAME"><br><br>
                        <button type="submit">Add Vehicle</button>
                    </form>
                </center>
            </div>
        </div>
    </body>
    
    <script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{% static 'sensors/js/Rx.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<style>
.login-page {
  width: 370px;
  padding: 10% 0 0;
  margin: auto;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 50px;
  padding: 30px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 50px;
  padding: 30px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 10px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #4CAF50;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.form button:hover,.form button:active,.form button:focus {
  background: #43A047;
}
body {
  /*background: #76b852; /* fallback for old browsers 
  background-image: url({% static 'users/img/bg/bg-9.jpg' %});*/
  background: -webkit-linear-gradient(right, #76b852, #8DC26F);
  background: -moz-linear-gradient(right, #76b852, #8DC26F);
  background: -o-linear-gradient(right, #76b852, #8DC26F);
  background: linear-gradient(to left, #76b852, #8DC26F);
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;      
}

</style>
</html>

users/templates/users/addplant.html
<html>
    <head>

        {% load staticfiles %}
        <title>DILUTE</title>
        <script src="https://use.fontawesome.com/a2c08f3da1.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
        <link rel="shortcut icon" href="{% static 'users/img/logo-image.jpg' %}">
    </head>
    <body style="background-image: url({% static 'users/img/bg/main1.jpg' %});">
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarTogglerDemo01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'users:homepage' %}">Home </a>
                    </li>
                </ul>
                {% if 'name' in request.session %}
                    Hello {{ request.session.name }} !
                {% endif %}
                <ul class="navbar-nav ml-auto">
                    <!--li class="nav-item">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact Us</a>
                    </li-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'sensors:logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="login-page">
            <div class="form">
                <center>
                    <form name="myform1" role="form" action="{% url 'users:addplant' %}" method="post" class="register-form">
                        <img src="{% static 'users/img/logo-image.jpg' %}" alt="" height="150px" width="150px" />
                        {% csrf_token %}
                        <input type="text" name="plantname" placeholder="PLANT NAME"><br><br>
                        <button type="submit">Add Plant</button>
                    </form>
                </center>
            </div>
        </div>
    </body>
    
    <script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{% static 'sensors/js/Rx.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<style>
.login-page {
  width: 370px;
  padding: 10% 0 0;
  margin: auto;
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 50px;
  padding: 30px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form {
  position: relative;
  z-index: 1;
  background: #FFFFFF;
  max-width: 360px;
  margin: 0 auto 50px;
  padding: 30px;
  text-align: center;
  box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
}
.form input {
  font-family: "Roboto", sans-serif;
  outline: 0;
  background: #f2f2f2;
  width: 100%;
  border: 0;
  margin: 0 0 15px;
  padding: 10px;
  box-sizing: border-box;
  font-size: 14px;
}
.form button {
  font-family: "Roboto", sans-serif;
  text-transform: uppercase;
  outline: 0;
  background: #4CAF50;
  width: 100%;
  border: 0;
  padding: 15px;
  color: #FFFFFF;
  font-size: 14px;
  -webkit-transition: all 0.3 ease;
  transition: all 0.3 ease;
  cursor: pointer;
}
.form button:hover,.form button:active,.form button:focus {
  background: #43A047;
}
body {
  /*background: #76b852; /* fallback for old browsers 
  background-image: url({% static 'users/img/bg/bg-9.jpg' %});*/
  background: -webkit-linear-gradient(right, #76b852, #8DC26F);
  background: -moz-linear-gradient(right, #76b852, #8DC26F);
  background: -o-linear-gradient(right, #76b852, #8DC26F);
  background: linear-gradient(to left, #76b852, #8DC26F);
  font-family: "Roboto", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;      
}

</style>
</html>

users/templates/users/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
</div>
{% endfor %}